### ISSUE TITLE
Unable to use model potential

### ISSUE THREAD

**Issue by reinhard405** [pairinteraction/pairinteraction#105]
Hello,

When using version 0.9.5 of the pair potential GUI program, I am unable to use the option "Calculate radial matrix elements from model potentials" any time I choose a basis size (in GHz) which results in a matrix larger than 100x100.  If I do this, the program aborts the calculation within several seconds of starting. This is true for both a Stark map and a pair potential calculation.  If I choose to calculate radial matrix elements using Whitaker functions, the program works fine.  I am running Windows 10.

Thanks,
Aaron

**Comment by seweber** [comment]
Dear Aaron, Thanks for your bug report. I installed pairinteraction 0.9.5 under Windows 10, but am not able to reproduce the problem. What has been the last output in the terminal window? Is the problem always occurring or just for specific settings? You can try to go into the configuration menu and press <kbd>Clear cache</kbd>, <kbd>Reset system settings</kbd>, and <kbd>Reset plot settings</kbd> (before resetting everything to its default values you might save your current settings using the file menu). If you now run <kbd>Calculate potential</kbd> with the default settings, is the problem still occurring? Sebastian

**Comment by reinhard405** [comment]
Hi Sebastian,

Thank you for your reply.  I think I can now isolate the source of the problem.  If I choose delta_L=3 or 4 and delta_m=-1 (unrestricted), the program works fine, even with the model potential selected.  If I choose delta_L=-1 and delta_m=3 or 4 then the program crashes.  Perhaps a huge matrix is being populated with unneeded high L-states and it gets too large and crashes?  

In an old version of the program on a different computer (version 0.7 I believe) I was able to use delta_L=-1 and delta_m=3 or 4 with the model potential and it would work.  Using the current version of the program, I can choose a large two atom basis with delta_L=4 and delta_m=-1 and use the model potential and it will still work, even though the matrix is 3289x3289.  So I’m not totally sure.

However, it seems like the right solution is to restrict the range of the allowed L values.  Does this make sense?

Thanks for your help,
Aaron

**Comment by hmenke** [comment]
My suspicion is that `delta_L` is silently converted to an unsigned integer internally, so -1 actually becomes 2^64-1 which is pretty big.

**Comment by seweber** [comment]
We have now published a [new release](https://github.com/pairinteraction/pairinteraction/releases/tag/v0.9.6-alpha) which supposedly fixes the bug.

**Comment by reinhard405** [comment]
Great - thank you again for your help.

Best,
Aaron
