### ISSUE TITLE
Can't Make Pair Potential Plot With Nonzero Angle

### ISSUE THREAD

**Issue by reinhard405** [pairinteraction/pairinteraction#111]
I am using the patched version of V0.9.6alpha which was posted on Feb 26 in response to issue #108.  I am computing pair potentials and everything works as expected when I choose an interaction angle of 0 degrees.  When I choose any nonzero value for the interaction angle, the program crashes.  

When I hit calculate potential, in the status bar at the bottom of the window, it briefly says.  “Field maps: calculate overlap states.”  The program then crashes, with the following message in the command line: “ImportError: cannot import name 'factorial' ”.

I went back and installed V0.9.5 and the pair potential graphs work fine with nonzero angle.  I am using Windows 10.

Thanks for your help,
Aaron

**Comment by hmenke** [comment]
In version 1.3.0 SciPy removed `factorial` from `misc` and moved it to `special`.  Because the version of SciPy is not pinned in our build system, the last build picked up the newer version which has this problem.  Should be fixed by #112.
