### ISSUE TITLE
Installation fails on windows with 0.9.6 alpha, No module named 'pkg_resources.py2_warn'

### ISSUE THREAD

**Issue by zzpwahaha** [pairinteraction/pairinteraction#114]
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_pkgres.py", line 11, in <module>
  File "c:\miniconda36-x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 621, in exec_module
  File "site-packages\pkg_resources\__init__.py", line 86, in <module>
ModuleNotFoundError: No module named 'pkg_resources.py2_warn'
[32848] Failed to execute script pyi_rth_pkgres

I tried to downgrade setuptools to 44.0.0 as suggested [here](https://stackoverflow.com/questions/59035724/python-error-no-module-named-pkg-resources) but it does not work

Below is my installed package for reference
Package                            Version
---------------------------------- -----------------
-andas                             1.0.1
-rc-alkali-rydberg-calculator      2.2.14
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.9.12
anaconda-project                   0.8.3
apptools                           4.4.0
arc                                1.0
ARC-Alkali-Rydberg-Calculator      2.2.15
asn1crypto                         1.3.0
asteval                            0.9.18
astroid                            2.3.3
astropy                            4.0.1.post1
atomicwrites                       1.3.0
attrs                              19.3.0
Babel                              2.8.0
backcall                           0.1.0
backports.functools-lru-cache      1.6.1
backports.os                       0.1.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
beautifulsoup4                     4.9.0
bibtexparser                       1.1.0
bitarray                           1.2.1
bkcharts                           0.2
bleach                             3.1.4
bokeh                              2.0.1
boltons                            20.0.0
boto                               2.49.0
Bottleneck                         1.3.2
certifi                            2020.4.5.1
cffi                               1.14.0
chardet                            3.0.4
click                              7.1.1
cloudpickle                        1.4.0
clyent                             1.2.2
cmake                              3.17.1
colorama                           0.4.3
comtypes                           1.1.7
conda                              4.8.3
conda-build                        3.18.11
conda-package-handling             1.6.0
conda-verify                       3.4.2
configobj                          5.0.6
contextlib2                        0.6.0.post1
cryptography                       2.8
cssselect                          1.1.0
cycler                             0.10.0
Cython                             0.29.16
cytoolz                            0.10.1
dask                               2.15.0
decorator                          4.4.2
defusedxml                         0.6.0
distributed                        2.15.0
docutils                           0.16
doi2bib                            0.3.0
entrypoints                        0.3
envisage                           4.9.2
et-xmlfile                         1.0.1
face                               20.1.1
fastcache                          1.1.0
filelock                           3.0.12
fire                               0.2.1
Flask                              1.1.2
fsspec                             0.7.1
future                             0.18.2
gevent                             1.4.0
ghostscript                        0.6
glob2                              0.7
glom                               19.10.0
greenlet                           0.4.15
h5py                               2.10.0
HeapDict                           1.0.1
html5lib                           1.0.1
hypothesis                         5.8.3
idna                               2.9
imageio                            2.8.0
imagesize                          1.2.0
importlib-metadata                 1.5.0
ipykernel                          5.1.4
ipython                            7.13.0
ipython-genutils                   0.2.0
ipywidgets                         7.5.1
isort                              4.3.21
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.16.0
Jinja2                             2.11.2
joblib                             0.14.1
json5                              0.9.4
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.2
jupyter-console                    6.1.0
jupyter-core                       4.6.3
jupyterlab                         1.2.6
jupyterlab-server                  1.1.0
keyring                            21.1.1
kiwisolver                         1.1.0
krotov                             1.1.0
lazy-object-proxy                  1.4.3
libarchive-c                       2.9
line-profiler                      2.1.1
llvmlite                           0.32.0
lmfit                              1.0.0
locket                             0.2.0
loky                               2.6.0
lxml                               4.5.0
MarkupSafe                         1.1.1
matplotlib                         3.2.0
mccabe                             0.6.1
menuinst                           1.4.16
mistune                            0.8.4
mkl-fft                            1.0.15
mkl-random                         1.1.0
mkl-service                        2.3.0
mock                               4.0.2
more-itertools                     8.2.0
mpmath                             1.1.0
msgpack                            1.0.0
multipledispatch                   0.6.0
navigator-updater                  0.2.1
nbconvert                          5.6.1
nbformat                           5.0.4
networkx                           2.4
nltk                               3.4.5
nose                               1.3.7
notebook                           6.0.3
numba                              0.49.0
numexpr                            2.7.1
numpy                              1.18.1
numpydoc                           0.9.2
odeintw                            0.1.1
olefile                            0.46
openpyxl                           3.0.3
orthopy                            0.6.3
packaging                          20.3
pairinteraction                    0.9.6a0
pandas                             1.0.1
pandocfilters                      1.4.2
parse                              1.15.0
parso                              0.6.2
partd                              1.1.0
path.py                            11.5.0
pathlib2                           2.3.5
patsy                              0.5.1
pep8                               1.7.1
pickleshare                        0.7.5
Pillow                             7.0.0
Pint                               0.11
pip                                20.0.2
pkginfo                            1.5.0.1
plotly                             4.5.4
pluggy                             0.13.1
ply                                3.11
prometheus-client                  0.7.1
prompt-toolkit                     3.0.4
psutil                             5.7.0
py                                 1.8.1
pycodestyle                        2.5.0
pycosat                            0.6.3
pycparser                          2.20
pycrypto                           2.6.1
pycurl                             7.43.0.5
pyface                             7.0.0
pyflakes                           2.2.0
Pygments                           2.6.1
pylint                             2.4.4
pyodbc                             4.0.0-unsupported
pyOpenSSL                          19.1.0
pyparsing                          2.4.6
PyQt5                              5.14.2
PyQt5-sip                          12.7.2
pyquery                            1.4.1
pyreadline                         2.1
pyrsistent                         0.16.0
PySocks                            1.7.1
pytest                             5.4.1
pytest-arraydiff                   0.3
pytest-astropy                     0.8.0
pytest-astropy-header              0.1.2
pytest-doctestplus                 0.5.0
pytest-openfiles                   0.4.0
pytest-remotedata                  0.3.2
python-dateutil                    2.8.1
pytz                               2019.3
PyWavelets                         1.1.1
pywebcopy                          6.1.1
pywigxjpf                          1.11
pywin32                            227
pywin32-ctypes                     0.2.0
pywinpty                           0.5.7
PyYAML                             5.3.1
pyzmq                              18.1.1
QtAwesome                          0.7.0
qtconsole                          4.7.3
QtPy                               1.9.0
quadpy                             0.14.11
qutip                              4.5.0
requests                           2.23.0
retrying                           1.3.3
rope                               0.16.0
ruamel-yaml                        0.15.87
scikit-image                       0.16.2
scikit-learn                       0.22.1
scipy                              1.4.1
seaborn                            0.10.0
Send2Trash                         1.5.0
setuptools                         46.4.0
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.14.0
snowballstemmer                    2.0.0
sortedcollections                  1.1.2
sortedcontainers                   2.1.0
soupsieve                          2.0
Sphinx                             3.0.3
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.1
spyder                             3.3.6
spyder-kernels                     0.5.2
SQLAlchemy                         1.3.16
statsmodels                        0.11.0
sympy                              1.5.1
tables                             3.6.1
tblib                              1.6.0
termcolor                          1.1.0
terminado                          0.8.3
testpath                           0.4.4
threadpoolctl                      2.0.0
toolz                              0.10.0
tornado                            6.0.4
tqdm                               4.45.0
traitlets                          4.3.3
traits                             6.0.0
traitsui                           7.0.0
typing-extensions                  3.7.4.1
uncertainties                      3.1.2
unicodecsv                         0.14.1
uniseg                             0.7.1
urllib3                            1.25.8
vtk                                9.0.0
w3lib                              1.21.0
wcwidth                            0.1.9
webencodings                       0.5.1
Werkzeug                           1.0.1
wheel                              0.34.2
widgetsnbextension                 3.5.1
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.12.1
xlrd                               1.2.0
XlsxWriter                         1.2.8
xlwings                            0.18.0
xlwt                               1.3.0
xmltodict                          0.12.0
zict                               2.0.0
zipp                               2.2.0

**Comment by hmenke** [comment]
I think this was already reported in #108 fixed in https://github.com/pairinteraction/pairinteraction/commit/7ee77d83d0a885e9fe2db234e9b451604377da71.
Can you try the installer from here? https://ci.appveyor.com/api/buildjobs/klri39p631f3q6oe/artifacts/build%2Fpairinteraction-install-windows.exe

**Comment by hmenke** [comment]
This is now fixed in the [0.9.7 release](https://github.com/pairinteraction/pairinteraction/releases/tag/v0.9.7-alpha). Thanks for reporting.
