### ISSUE TITLE
Package new release

### ISSUE THREAD

**Issue by Patschke** [pairinteraction/pairinteraction#126]
It would be convenient if an up to date version could be packaged. The latest version (0.9.7alpha) is from July 2020 and crashes for me with an `AttributeError: module 'PyQt5.QtGui' has no attribute 'QDialog'` error message that has already be fixed in db19fa6815c9e7d5af3159b02fa55300b516073f. Having to build from source is always somewhat mildly annoying.

**Comment by hmenke** [comment]
We actually have draft release for [v0.9.8-alpha](https://github.com/pairinteraction/pairinteraction/releases/tag/untagged-e88322f60f772d8c7e85) sitting around. I actually can't think of anything holding this back. @seweber Can you please click the button?

**Comment by seweber** [comment]
Yes, we can publish the new release (@hmenke, I actually was waiting for your confirmation that we can proceed with the release, seems as there was somehow a misunderstanding). The new release will be online by tomorrow at the latest.

**Comment by seweber** [comment]
The new release is published now. Among others, we updated dependencies so that the issue should be solved by this release. For a changelog, see  [v0.9.8-alpha](https://github.com/pairinteraction/pairinteraction/releases/tag/v0.9.8-alpha).

**Comment by Patschke** [comment]
I'd again like to ask to package a new release. Running latest version of numpy (1.24) `np.int` is no longer deprecated but removed from numpy. The current release of pairinteraction is therefore incompatible with latest numpy, an issue that has been fixed with the last commit. 58f82a9
