### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by Patschke** [pairinteraction/pairinteraction#150]
On my system the current master branch won't build. The first error encountered is
```console
[...]
-- Found LAPACK: /usr/lib/liblapack.so;/usr/lib/libblas.so  
-- Looking for LAPACKE_dsyev
-- Looking for LAPACKE_dsyev - not found
CMake Error at pairinteraction/CMakeLists.txt:202 (message):
  No working LAPACKE detected


-- Configuring incomplete, errors occurred!
==> ERROR: A failure occurred in build().
```
To overcome this I added the build flag `-DBLA_VENDOR=MKL` to my `cmake` call. That option is not listed in the existing build options (at least not in the list here: https://www.pairinteraction.org/pairinteraction/sphinx/html/installation.html#build-options), but I figured that it was worth a try from reading the last commits. 

I suggest adding a documentation of that flag to the installation guide. 

The next error popping up was this:

```console
[...]
[...]/python-pairinteraction/src/pairinteraction-master/pairinteraction/Cache.hpp:61:24: error: ‘runtime_error’ is not a member of ‘std’
   61 |             throw std::runtime_error("Cache smashing detected!");

[...]/python-pairinteraction/src/pairinteraction-master/pairinteraction/Cache.hpp:26:1: note: ‘std::runtime_error’ is defined in header ‘<stdexcept>’; did you forget to ‘#include <stdexcept>’?
   25 | #include <unordered_map>
  +++ |+#include <stdexcept>
   26 | 
```

which was fixed for me exactly the way the error log suggested: Adding an include `#include <stdexcept>` to the `Cache.hpp`. 

I am not an expert on C++, so I have no real idea in which way my build system is misconfigured that end up in those errors, but I'd guess that adding this line might not be the worst idea?

Not sure what specific information on my system are required to reproduce this issue. I use GCC 13.1.1 20230429 on a system running Arch Linux 6.3.1-arch1-1.

**Comment by hmenke** [comment]
You can set `-DWITH_LAPACK=Off` which will obviously skip the LAPACK detection and use the eigensolver of the Eigen library instead.

I think `-DBLA_VENDOR=MKL` does exactly nothing because `MKL` is not a valid BLAS/LAPACK Vendors according to the documentation: https://cmake.org/cmake/help/latest/module/FindBLAS.html#blas-lapack-vendors

If you want to build pairinteraction against MKL, you have to install [`intel-oneapi-mkl`](https://archlinux.org/packages/community-testing/x86_64/intel-oneapi-mkl/) and source the environment variables `. /opt/intel/oneapi/mkl/2023.1.0/env/vars.sh`. (untested)

**Comment by hmenke** [comment]
Can you please install [`lapacke`](https://archlinux.org/packages/extra/x86_64/lapacke/) and try again with https://github.com/pairinteraction/pairinteraction/commit/b54ed689db02d292df4f1a41c11582e695d97b01?

**Comment by Patschke** [comment]
lapacke 3.11.0-2 is installed, the build still fails with the same error using your last commit:
<details>
<summary> Full Log </summary>
```console
-- CMake version: 3.26.3
-- The CXX compiler identification is GNU 13.1.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.40.1") 
fatal: No names found, cannot describe anything.
CMake Warning at CMakeLists.txt:52 (message):
  Git failed to determine the version of the pairinteraction software.




-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5") found components: CXX 
-- Could NOT find MKL (missing: MKL_DIR)
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1") 
-- Checking for module 'mkl-dynamic-lp64-seq'
--   Package 'mkl-dynamic-lp64-seq', required by 'virtual:world', not found
-- Looking for sgemm_
-- Looking for sgemm_ - not found
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Found BLAS: /usr/lib/libblas.so  
-- Looking for cheev_
-- Looking for cheev_ - not found
-- Looking for cheev_
-- Looking for cheev_ - found
-- Found LAPACK: /usr/lib/liblapack.so;/usr/lib/libblas.so  
-- Looking for LAPACKE_dsyev
-- Looking for LAPACKE_dsyev - not found
CMake Error at pairinteraction/CMakeLists.txt:202 (message):
  No working LAPACKE detected

-- Configuring incomplete, errors occurred!

```

</details>

**Comment by Patschke** [comment]
Yep, works fine! Thank you.
