### ISSUE TITLE
Saving Data from GUI fails when Overlap set to not-inluded State

### ISSUE THREAD

**Issue by Patschke** [pairinteraction/pairinteraction#174]
When setting the `Overlap matrix element` in the `plot settings` tab to `overlap with state below` and choosing a state, that has not been part of the basis that is used, saving data will fail. (E.g. computing a stark map for around the 40S state while forgetting that the overlap still targets the 80S state). 

The error shown is:
```python
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pairinteraction_gui/pairinteraction_app/app.py", line 3165, in saveResult
    self.saveToZipfile(filename, idx)
  File "/usr/lib/python3.11/site-packages/pairinteraction_gui/pairinteraction_app/app.py", line 3243, in saveToZipfile
    data["numOverlapvectors"] = self.stateidx_field[idx][NO_BN].shape[0]
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'shape'
```

As a result, a zip-file will be created and saved, that does only include the plot png and settings files, but no data. 

This seems easy to fix, I could look into that and create a PR if you don't have time to do so.

**Comment by johannes-moegerle** [comment]
Thank you for the bug report, this should be fixed in 0b816715c880c806a0abd8d55c5c4b5ce4884c78
