### ISSUE TITLE
Rydberg Pair Potentials Under External Fields calculation not working for atoms other than Rubidium

### ISSUE THREAD

**Issue by wu-michelle** [pairinteraction/pairinteraction#175]
The example code for Rydberg pair potentials under external field calculation doesn't seem to work for atoms other than Rubidium. I was trying to use it on Cesium but for energy vs distance plot under different electric fields, but it would just give energy = 0 result.

**Comment by Patschke** [comment]
For me it seems like Cesium works just as well. Did you check, that the other settings are reasonable as well? 
If you just change 
```python
state_one = pi.StateOne("Rb", 61, 2, 1.5, 1.5)
```
to 
```python
state_one = pi.StateOne("Cs", 61, 2, 1.5, 1.5)
```
in the example code, I don't think that there are any pair states around for the limits of $\pm1 \mathrm{GHz}$ and fields of B=6.9 G from the example. As a result, you effectively diagonalize a 1-state hamiltonian, which will show a constant energy = 0 line. I'd guess the Rb example has been chosen in a way, that it looks nice. 

If I set e.g. 
```python
distances = np.linspace(16, 7, 100)  # µm
efields = [0, 0.005]  # V/cm
bfield = 1  # Gauss
state_one = pi.StateOne("Cs", 97, 2, 1.5, 1.5)
```
and increase the energy limit to $\pm2 \mathrm{GHz}$
```python
    system_two.restrictEnergy(state_two.getEnergy() - 2, state_two.getEnergy() + 2)
```

I end up with a plot that looks like it "does something". Of course, I did not check if the restrictions on the basis size are relaxed enough that this is a physically meaningful result (it might not have been converged yet and needs more basis states to do so) - I just wanted to check, if it works.
![Figure_1](https://github.com/pairinteraction/pairinteraction/assets/17853362/4aab5777-eec5-4141-97c1-282c1a1adecf)
