### ISSUE TITLE
Error saving data (TypeError in ImageExporter.py)

### ISSUE THREAD

**Issue by juliusdh** [pairinteraction/pairinteraction#52]
When saving a Pair Potential calculation on my system running Windows 10 (installed using the Windows `exe`) I get the following error:

````
Traceback (most recent call last):
  File "C:\Program Files\pairinteraction\gui\pairinteraction\app.py", line 2877, in saveResult
    self.saveToZipfile(filename, idx)
  File "C:\Program Files\pairinteraction\gui\pairinteraction\app.py", line 2895, in saveToZipfile
    image = exporter.export(toBytes=True)
  File "C:\Program Files\pairinteraction\gui\pairinteraction\pyqtgraph\exporters\ImageExporter.py", line 70, in export
    print self.params['width']
TypeError: 'float' object cannot be interpreted as an integer
````

I explored the Python code a bit and `print`ed `self.params['width']` and `self.params['height']` in ImageExporter.py right before line 70 where this error occurs. For some reason the value of `self.params['width']` is 2470.5885..., not exactly an integer, which I can imagine causes problems here. I tried looking into it further, but it's not exactly clear to me where this behavior comes from.

**Comment by hmenke** [comment]
Thank you very much for reporting this error.  It seems like this is an issue of `pyqtgraph`.  We will nevertheless look into it.  Please also note, that we only test pairinteraction on Windows 7.
