### ISSUE TITLE
Boost dependencies missing from documentation

### ISSUE THREAD

**Issue by mfe5003** [pairinteraction/pairinteraction#67]
In order to make cmake happy on Unbuntu 17.04 I also needed to install the following packages:

`libboost-program-options-dev`
`libboost-test-dev`

**Comment by hmenke** [comment]
Oops.  I haven't updated the Wiki in a long time.  Now it should be more up-to-date.  In the upcoming Python interface we are going to use many more Boost modules, which is why I put `libboost-all-dev` in the installation guide.

Thanks for the info!
