### ISSUE TITLE
Distribute Windows version via Anaconda Cloud

### ISSUE THREAD

**Issue by hmenke** [pairinteraction/pairinteraction#81]
That would release us from the burden to provide a Windows installer.
https://docs.anaconda.com/anaconda-cloud/user-guide/tasks/work-with-packages#cloud-conda-packages

Alternatively, distribute via PyPI, so that everyone can just `pip install pairinteraction`.
https://wiki.python.org/moin/CheeseShopTutorial#Submitting_Packages_to_the_Package_Index

**Comment by seweber** [comment]
I would tend to keep the Windows installer. Without the installer, the user would always have to install a Python distribution by its own, even if the user just likes to use the GUI. Besides, providing the stand-alone Windows installer ensures that the pairinteraction GUI cannot be broken through changes of the user's Python environment (at least in the past, there were occasional problems with some updates of Python libraries).

Perhaps, for users of the pairinteraction Python library, a Conda package could be nice to have in addition.

**Comment by seweber** [comment]
Python wheels of pairinteraction are now distributed via [PyPI](https://pypi.org/project/pairinteraction/) for GNU/Linux, Mac OS X, and Windows.
