### ISSUE TITLE
Issues with macOS High Sierra

### ISSUE THREAD

**Issue by AurynVg** [pairinteraction/pairinteraction#91]
Hi,

I am wondering whether the interface has problems with High Sierra. I attach a screenshot where I try to replicate one of the screenshots you have on the webpage 
https://pairinteraction.github.io/pairinteraction/sphinx/html/index.html

I cannot see the lines separate but just a one big block.

Thanks in advance for your help!

![screenshot_2018-07-27_17 10 11](https://user-images.githubusercontent.com/32542945/43350900-31254c8a-91c0-11e8-89bd-4ee3b255a6bd.png)

**Comment by seweber** [comment]
Now, we have tested the software on a computer with macOS High Sierra. There, it also works fine. Thus, I guess that the issue was caused by wrong settings or a broken cache. The commands given in my last post or <kbd>Configuration > Clear cache</kbd> should hopefully fix the issue.

**Comment by AurynVg** [comment]
Hi,
sorry for my late reply.
Please find below a new screenshot. It works better but still something is wrong:
![captura de pantalla 2018-07-31 a las 12 07 30](https://user-images.githubusercontent.com/32542945/43481286-5fe76024-94ba-11e8-872d-5f19025b538f.png)

**Comment by AurynVg** [comment]
Apologies, it was the axis. Here it is:

![captura de pantalla 2018-07-31 a las 12 09 38](https://user-images.githubusercontent.com/32542945/43481372-a69178a2-94ba-11e8-8f73-746a63b22d43.png)

Thank you!
