### ISSUE TITLE
problem with customizing species in database 

### ISSUE THREAD

**Issue by westlike666** [pairinteraction/pairinteraction#98]
Hi there,

I am trying to generate a starkmap of a new specie using the pairinteraction but I run into a issue with inserting new species to the database. The only database file I found was quantum_defects.db in the databases folder.  Inserting new species to this file was not recognized even using the command cache.setDefectDB() according to the tutorial. I found that the quantum_defects.db is not read at all because changing or deleting its data does not give any difference on the result.  I am wondering if the calculation is based on some hidden built-in properties of the species rather than the quantum_defect.db file, but I fail to find where those information is from. Would you like to explain more specific how it works? Thank you in advance.

Ruoxi

**Comment by hmenke** [comment]
Dear Ruoxi,

Thanks for your interest in pairinteraction and your bug report.  Could you please provide a minimal example that reproduces your problem?  It will make it much easier for us to locate and fix the issue.

The following code creates a new database with model potentials and quantum defects and uses them to calculate a radial matrix element.  This should be a good starting point for a minimal example.
```python
import os
import sqlite3
from pairinteraction import pireal as pi

if not os.path.exists("./cache"):
    os.makedirs("./cache")
cache = pi.MatrixElementCache("./cache")

conn = sqlite3.connect("database.db")
c = conn.cursor()
c.execute(r"DROP TABLE IF EXISTS `model_potential`;")
c.execute(r"CREATE TABLE `model_potential` ( `element` text,`L` int,`ac` real,`Z` int,`a1` real,`a2` real,`a3` real,`a4` real,`rc` real);")
c.execute(r"INSERT INTO `model_potential` VALUES('H',0,'0.0',1,'0.0','0.0','0.0','0.0','0.0');")
c.execute(r"DROP TABLE IF EXISTS `rydberg_ritz`;")
c.execute(r"CREATE TABLE `rydberg_ritz` ( `element` text,`L` int,`J` real,`d0` real,`d2` real,`d4` real,`d6` real,`d8` real,`Ry` real);")
c.execute(r"INSERT INTO `rydberg_ritz` VALUES('H',0,'0.5','0.0','0.0','0.0','0.0','0.0','109728.64');")
c.execute(r"INSERT INTO `rydberg_ritz` VALUES('H',1,'0.5','0.0','0.0','0.0','0.0','0.0','109728.64');")
conn.commit()
conn.close()

cache.setDefectDB("database.db")

state_i = pi.StateOne("H", 1, 0, 0.5, 0.5)
state_f = pi.StateOne("H", 2, 0, 0.5, 0.5)

print(cache.getRadial(state_f, state_i, 1))
```

**Comment by westlike666** [comment]
Hi Henri,

Thank you very much for your reply.
Here is an example that tries to generate a Stark map for new species NO. I
modified the database as attached as quantum_defects.db, by just copying
and paste the Rb data and change its name to NO.  The code works if I
change it to 'Rb' but not for 'NO'.

Any suggestions?

import numpy as np

# Plotting
import matplotlib.pyplot as plt

# Operating system interfaces
import os

# If the pairinteraction library was not installed via pip or using a Linux
package manager,
# we have to manually add the library path to the Python package search
path. If the library
# was for example installed using the Windows or macOS installers from
GitHub releases, this
# can be done by uncomment the following code block:
#
# import sys
# if sys.platform == "darwin":
#
sys.path.append("/Applications/pairinteraction.app/Contents/Resources")
# elif sys.platform == "win32":
#     sys.path.append("C:\Program Files\pairinteraction")

# pairinteraction :-)
from pairinteraction import pireal as pi


if not os.path.exists("./test/cache"):
    os.makedirs("./test/cache")

cache = pi.MatrixElementCache("./test/cache")

cache.setDefectDB("./databases/quantum_defects.db")


# Define values of E-field pointing into the direction of the quantization
axis
array_efield = np.linspace(0,10,1000) # V/cm

# Define state for which the Stark map should be calculated
state = pi.StateOne("NO", 40, 1, 0.5, 0.5)

# Initialize a system comprising one rubidium Rydberg atom
system = pi.SystemOne(state.getSpecies(), cache)

# Consider only states with similar energy and quantum numbers as the
defined state
system.restrictEnergy(state.getEnergy()-100, state.getEnergy()+100)
system.restrictN(state.getN()-1, state.getN()+1)
system.restrictL(state.getL()-10, state.getL()+10)

# Because E-field points along quantization axis, the magnetic quantum
number is conserved
system.setConservedMomentaUnderRotation([state.getM()])

# Diagonalize the Hamiltonian of the system for different E-fields
array_eigenvalues = []
array_overlaps = []

for efield in array_efield:
    system.setEfield([0, 0, efield])

    # Diagonalize system, pruning values smaller than 1e-3 from eigenvectors
    system.diagonalize(1e-3)

    # Store the eigenenergies

array_eigenvalues.append(system.getHamiltonian().diagonal()-state.getEnergy())

    # Store the overlap of the eigenstates with the defined state
    array_overlaps.append(system.getOverlap(state))

array_eigenvalues = np.ravel(array_eigenvalues)
array_overlaps = np.ravel(array_overlaps)
array_efield = np.repeat(array_efield, system.getNumBasisvectors())

# Plot Stark map, the color code visualizes overlap of eigenstates with
defined state
fig=plt.scatter(array_efield, array_eigenvalues, 0.1, array_overlaps)
plt.xlabel("Electric field (V/cm)")
plt.ylabel("Energy (GHz)")

**Comment by westlike666** [comment]
Here is the attached database file

**Comment by westlike666** [comment]
I realized that the customized database file can be passed to getRadial to evaluate the radial matrix elements, which is helpful as it is the main computation task.  However it fails to read the model potential of the new database to generate the whole Hamiltonian.  It would be nice and convenient if this problem can be solved.  

Many thanks!

**Comment by hmenke** [comment]
Thank you very much for posting the example and your further investigation, that is very helpful.  I will see whether I can cook up a solution this weekend.

**Comment by seweber** [comment]
We have now developed a bug fix. Since it will probably take until mid of August before a new official version of the pairinteraction software gets released, I put a version of the software containing the fix on [my fork of the repository](https://github.com/seweber/pairinteraction/releases/tag/v0.9.6-prealpha5) and on [TestPyPI](https://test.pypi.org/project/pairinteraction/).

After installing this version of the software, it should be possible to make your code work by passing the `MatrixElementCache` object to `state.getEnergy()`, i.e., you have to call `state.getEnergy(cache)`. I hope that this solves the issue. Thanks again for your bug report!
